### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by Lightmani** [zhboner/realm#1]
1、增加配置文件，以便支持多端口

2、增加守护进程，避免进程挂掉

**Comment by zhboner** [comment]
收到了。这两项是下一步更新的地方

**Comment by zhboner** [comment]
配置文件和多端口的功能已经更新了 [Realm v1.2-beta.1](https://github.com/zhboner/realm/releases)

**Comment by Lightmani** [comment]
配置文件不支持多个地址吗？
我尝试这样写，无法运行


{
    "listening_addresses": ["0.0.0.0"],
    "listening_ports": ["1"],
    "remote_addresses": ["3"],
    "remote_ports": ["443"]
},
{
    "listening_addresses": ["0.0.0.0"],
    "listening_ports": ["2"],
    "remote_addresses": ["1"],
    "remote_ports": ["443"]
},
{
    "listening_addresses": ["0.0.0.0"],
    "listening_ports": ["1"],
    "remote_addresses": ["1"],
    "remote_ports": ["443"]
}

**Comment by zhboner** [comment]
你可以写成

···
{
"listening_addresses": ["0.0.0.0"],
"listening_ports": ["1", "2", "1"],
"remote_addresses": ["3", "1", "1"],
"remote_ports": ["443"]
}
···

**Comment by Lightmani** [comment]
当我这么做后，程序报错

 ./realm -c config.json 
thread 'main' panicked at 'Unmatched number of listening and remot ports', src/lib.rs:152:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by Lightmani** [comment]
解决了，remote port需要同样数量

**Comment by zhboner** [comment]
发布的是旧版本，稍后我上传一个新版

**Comment by zhboner** [comment]
[Realm v1.2-beta.2](https://github.com/zhboner/realm/releases/tag/v1.2-beta.2)

**Comment by Lightmani** [comment]
新版似乎有些问题
启动后没有任何报错，但是无法中转

配置如这样写的
{
"listening_addresses": ["0.0.0.0"],
"listening_ports": ["1", "2", "1"],
"remote_addresses": ["3", "1", "1"],
"remote_ports": ["443"]
}

**Comment by zhboner** [comment]
这是一个bug，已经修复。
