### ISSUE TITLE
增加限速功能

### ISSUE THREAD

**Issue by f4nff** [zhboner/realm#103]
增加单连接的限速功能,
限制单连接的上行/下行速率
防止突发高带宽被nat层Qos

我详细测试过,如果带宽在某个值以下,传输很稳定,
如果高于这个值就会被惩戒~~~~

**Comment by zephyrchien** [comment]
暂时对这功能没兴趣， 建议fork以后自行修改。 Realm的项目结构很简单， 只需要修改 `realm_io::copy` 就可以实现你想要的功能。
