### ISSUE TITLE
相同配置，中转机正常，落地机报错

### ISSUE THREAD

**Issue by lsbjkc** [zhboner/realm#104]
中转机日志及配置：
root@OS202305:/home/RealM# systemctl status realm
● realm.service - RealM
     Loaded: loaded (/etc/systemd/system/realm.service; disabled; vendor preset: enabled)
     Active: active (running) since Tue 2023-05-16 16:20:39 UTC; 37min ago
   Main PID: 2777 (realm)
      Tasks: 7 (limit: 7105)
     Memory: 728.0K
        CPU: 5ms
     CGroup: /system.slice/realm.service
             └─2777 /home/RealM/realm -c /home/RealM/config.toml

May 16 16:20:39 OS202305 systemd[1]: Started RealM.
root@OS202305:/home/RealM# cat /home/RealM/config.toml
[log]
level = "warn"
output = "/var/log/realm.log"

[network]
no_tcp = false
use_udp = true

[[endpoints]]
listen = "0.0.0.0:20478"
remote = "1.1.1.1:20478"
remote_transport = "tls;sni=www.speedtest.net;insecure"
------------------------------------------------------------------------------------------------------------------------
落地机日志及配置：
[root@KS202305 ~]# systemctl status realm
× realm.service - RealM
     Loaded: loaded (/etc/systemd/system/realm.service; disabled; preset: disabled)
     Active: failed (Result: exit-code) since Wed 2023-05-17 02:38:03 HKT; 6s ago
   Duration: 10ms
    Process: 57390 ExecStart=/home/RealM/realm -c /home/RealM/config.toml (code=exited, status=101)
   Main PID: 57390 (code=exited, status=101)
        CPU: 2ms

May 17 02:38:03 KS202305 systemd[1]: Started RealM.
May 17 02:38:03 KS202305 realm[57390]: thread 'main' panicked at 'tls: require cert and key or servername', /cargo/registry/src/index.crates.io-6f17d22bba15001f/kaminari-0.11.0/src/opt.rs:110:9
May 17 02:38:03 KS202305 realm[57390]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
May 17 02:38:03 KS202305 systemd[1]: realm.service: Main process exited, code=exited, status=101/n/a
May 17 02:38:03 KS202305 systemd[1]: realm.service: Failed with result 'exit-code'.
[root@KS202305 ~]# cat /home/RealM/config.toml
[log]
level = "warn"
output = "/var/log/realm.log"

[network]
no_tcp = false
use_udp = true

[[endpoints]]
listen = "0.0.0.0:20478"
remote = "127.0.0.1:21376"
listen_transport = "tls;sni=www.speedtest.net"
-------------------------------------------------------------------------------------------------------------------
提示tls要证书和key，但是我记得之前用“insecure”是不用证书的啊。

**Comment by lsbjkc** [comment]
抱歉，我太粗心了，把配置文件搞错了。。。

**Comment by omaidb** [comment]
你可以告诉我，listen_transport  和remote_transport 参数到底是怎么玩的嘛？
