### ISSUE TITLE
Is it possible to add a command-line function to check whether the syntax and parameters of the configuration file are correct.

### ISSUE THREAD

**Issue by omaidb** [zhboner/realm#110]
I use toml or json configuration files.
Is it possible to add a command-line tool to check whether the syntax and parameters of the configuration file are correct.
Because I just noticed that FTO and network.zero_copy are deprecated; I just realized I was using an unsupported parameter in the toml.

**Comment by zephyrchien** [comment]
Any unknown field in the config file will be ignored, only useful ones(listed in the doc) are left. So you dont need to worry about this..

**Comment by zephyrchien** [comment]
I'm planning to add some warnings where the user's input may lead to unexpected results.

**Comment by omaidb** [comment]
> I'm planning to add some warnings where the user's input may lead to unexpected results.

good idea
