### ISSUE TITLE
请问哪个参数支持故障转移

### ISSUE THREAD

**Issue by hzhengcy** [zhboner/realm#113]
请问哪个参数支持故障转移，A服务器断了后切换到B服务器，A服务器恢复后切换到A服务器

**Comment by betaxab** [comment]
目前不支持。 希望开发者能百忙之中抽出时间来看看。

@zephyrchien 急切需要故障转移功能。

**Comment by zephyrchien** [comment]
dup #82

最近比较忙， 不过我会尽快实现此功能
