### ISSUE TITLE
通过realm转发后无法实现NAT1

### ISSUE THREAD

**Issue by lin1123** [zhboner/realm#117]
经过测试，直连vless节点，能够正常NAT1。
通过转发的节点只能NAT4。

**Comment by zephyrchien** [comment]
我认为这种行为跟vless客户端/服务端实现有关， 并不是转发工具导致的。

**Comment by lin1123** [comment]
> 我认为这种行为跟vless客户端/服务端实现有关， 并不是转发工具导致的。

同样的客户端/服务端，一样的版本，节点一模一样的配置。直连的能NAT1，通过中转的全是NAT4。

**Comment by lin1123** [comment]
<img width="391" alt="image" src="https://github.com/zhboner/realm/assets/62827465/f7c34f2c-2ee0-4db9-953a-42c312005e48">
<img width="382" alt="image" src="https://github.com/zhboner/realm/assets/62827465/867deecd-0563-4d74-bb89-04d4c446ad27">
第一个直连，第二个中转，配置一样。都是UOT

**Comment by zephyrchien** [comment]
@lin1123  转发工具只是在Layer4单纯地转发TCP/UDP 。 你遇到的问题不是由转发工具导致的，对于转发工具也没有解决方案。

**Comment by lin1123** [comment]
能实现NAT1的两台VPS是独立IPv4，不能实现的是NAT的IPv4，这个会不会影响？

**Comment by zephyrchien** [comment]
@lin1123  我估计前者转发后也能过NAT1测试，  后者直连也无法过NAT1测试。。

**Comment by lin1123** [comment]
试过了，用独立V4转发到独立V4能实现NAT1，我在试试NAT v4转发到独立V4。

**Comment by lin1123** [comment]
尝试NATv4入站，然后通过独立V6转发到独立V6入站、独立V4出站，能实现NAT1.

**Comment by lin1123** [comment]
> 尝试NATv4入站，然后通过独立V6转发到独立V6入站、独立V4出站，能实现NAT1.

落地的v4与v6在同一网卡，不能实现NAT1的落地机不在一个网卡上。

**Comment by lin1123** [comment]
与转发工具无关，只要是NAT 的vps，就无法通过NAT1测试。感谢大佬的回复。
