### ISSUE TITLE
realm+dnsproxy DOH

### ISSUE THREAD

**Issue by univerioiln233** [zhboner/realm#118]
there is a service of dnsproxy at 127.0.0.1:53
If the realm listens to port 443, tls cannot be enabled, otherwise dns-doh cannot be used.
'''
[dns]
protocol = "tcp_and_udp"
nameservers = ["127.0.0.1:53"]
cache-size = 0
[network]

use_udp = true
tcp_timeout = 300
udp_timeout = 30

[[endpoints]]

listen = "[::]:443"

remote = "127.0.10.2:9443"
'''
如果realm监听443端口，不能开tls，否则dns-doh无法使用?不知道我理解的对不对

**Comment by zephyrchien** [comment]
realm开启tls监听的话会把tls转成tcp.

`dns-doh` 指的是dnsproxy提供的服务吗? 无法使用的主体是什么，需要具体描述一下使用场景。
