### ISSUE TITLE
TLS SNI proxy

### ISSUE THREAD

**Issue by almereyda** [zhboner/realm#119]
I'm currently using Traefik with the `HostSNI` TCP router for TLS connections to split them between different hosts, depending on condition.

It seems this could also be a useful feature for realm in secure environments.

**Comment by almereyda** [comment]
Would the `servername=` property in a `listen_transport` directive accept RegExp or Globbing wildcards?

https://github.com/zhboner/realm/blob/882c2e3c00e73aba97cddc02295a92a1daaaa1e8/examples/tls.toml#L9

**Comment by almereyda** [comment]
Following the link in the readme, this appears to be an upstream issue for [zephyrchien/kaminari](https://github.com/zephyrchien/kaminari).

**Comment by zephyrchien** [comment]
Actually the `servername=` field of `listen_transport` is used as a hint for generating self-signed certificates, not for dispatching backends.

**Comment by zephyrchien** [comment]
Realm with the `balance` module does allow multiple backends being bound to a single frontend. However the way to pick a backend is limited, currently just `load-balancer` and `hook`. `load-balancer` switches between backends automatically based on the strategy. `hooks` requires users to write dynamic libraries.

On the other hand, `sni` could be sniffed from the first several bytes at the TCP level(sni is one of the [TLS extensions](https://datatracker.ietf.org/doc/html/rfc6066#section-1.1)).

**Comment by zephyrchien** [comment]
I'm planning to refactor the whole project, providing a more flexible way to organize frontends/backends.
