### ISSUE TITLE
realm有多线程优化吗？在一台多核机器上，u单核性能比较差，经常吃满一个cpu，其他cpu好像不怎么动

### ISSUE THREAD

**Issue by yangyzp** [zhboner/realm#128]
realm有多线程优化吗？在一台多核机器上，u单核性能比较差，经常吃满一个核心，其他核心好像不怎么动

**Comment by zephyrchien** [comment]
多线程功能可以参考 [Build Options](https://github.com/zhboner/realm?tab=readme-ov-file#build-options) 中的 `multi-thread` (Github Release页面的预编译二进制都开启了此选项)

方便补充一下使用场景吗？ 如果开启了TLS, 可能CPU都消耗在加/解密上了。

**Comment by yangyzp** [comment]
中转ssr，采用realm+tls方式。我用的就是  Github Release页面的预编译二进制文件。但是似乎并没有用到多线程。是需要额外开启吗？

**Comment by zephyrchien** [comment]
不用手动开启， 默认用的就是多线程Runtime= =。但是单个连接同时只能被一个线程处理， 期间发生的CPU运算也没法被多线程分摊。。

**Comment by zephyrchien** [comment]
@E021ntox  不明白你的意思。 Realm是单进程程序，对于进程资源没有任何处理。

**Comment by zephyrchien** [comment]
@E021ntox  可以实现，但是 `SIGTERM`的默认处理就是直接退出，我觉得问题在于容器中的Realm没有收到信号。 [这边有篇相关的讨论](https://www.reddit.com/r/docker/comments/1039twp/how_do_i_make_my_container_handle_signals_and/)

**Comment by zephyrchien** [comment]
@E021ntox  我们可以再开一个Issue进行讨论
