### ISSUE TITLE
请问real是否支持tcp fast open?

### ISSUE THREAD

**Issue by yushum** [zhboner/realm#13]
我在中转服务器和落地服务器上都开启了tfo，但是通过realm中转后显示没有tfo，realm是否支持tfo呢?

**Comment by Anankke** [comment]
附议，希望添加 TFO 支持。

**Comment by zhboner** [comment]
暂时不能支持，原因见 

https://github.com/shadowsocks/shadowsocks-rust/issues/184#issuecomment-814927989
