### ISSUE TITLE
转发 https 问题求帮助

### ISSUE THREAD

**Issue by forxfoo** [zhboner/realm#130]
小白求帮助
场景如下：
有一个代理是 https 的如： https://2.2.2.2:2222 账号为 aaa，密码为 bbb

使用 realm 要怎么配置？

像这样配置，https 账号密码要怎么过去？

realm -u --log-level debug -l 127.0.0.1:10000 -r 2.2.2.2:2222

**Comment by zephyrchien** [comment]
不确定你那边的具体需求是什么, Realm本身不支持解析HTTPS代理协议, 只能把流量当作TCP直接转发

直接转发的情况下, 客户端把请求目标指向Realm即可.
客户端会经过Realm和服务端完成TLS握手, 再完成认证, 发送代理请求.
需要注意的客户端的直接向Realm发起请求, 发送的SNI可能导致服务端找不到匹配的证书.
