### ISSUE TITLE
Support include endpoints function

### ISSUE THREAD

**Issue by HanadaLee** [zhboner/realm#135]
In realm, endpoints are similar to the role of nginx servers. However, they can only be used in a single configuration file. If there are a large number of forwarding rules, it will be troublesome to manage the configuration file. I hope to implement endpoint-based file parsing.

Here is an example

realm.json
```
{
  "external_endpoints": "./endpoints/*.json",
  "endpoints": [
    {
      "listen": "0.0.0.0:5000",
      "remote": "1.1.1.1:443"
    },
    {
      "listen": "0.0.0.0:10000",
      "remote": "www.google.com:443"
    }
  ]
}
```
./endpoints/cloud.google.com.json
```
{
      "listen": "0.0.0.0:10001",
      "remote": "cloud.google.com:443"
}
```

**Comment by zephyrchien** [comment]
The proposal sounds good to me. Personally I would like to have HTTP API implemented first, the configuration file loading process will then go the API path.

**Comment by zephyrchien** [comment]
#141 would be helpful to reduce the complexity of managing config files.

**Comment by zephyrchien** [comment]
wait for #91
