### ISSUE TITLE
ghcr docker image missing

### ISSUE THREAD

**Issue by Detavern** [zhboner/realm#144]
Hi, it seems that the container image is missing.
I could not find it on the package [page](https://github.com/zhboner?tab=packages) too.
Is there still a visibility issue? #61

**Comment by zephyrchien** [comment]
Hey @Detavern, you are right. The docker repository is not properly configured while I do not have the access to fix it. Maybe oneday @zhboner would take a look at those issues.

**Comment by Detavern** [comment]
Glad to hear that.
