### ISSUE TITLE
故障转移功能

### ISSUE THREAD

**Issue by bingotl** [zhboner/realm#145]
remote":"111.111.111.1:111","extra_remotes": ["222.222.222.22:222""333.333.333.333:333"],

比如这个设置，那么流量只转发到111.111.111.1这台服务器，如果第1台没有响应，就标记为宕机。继续把流量转发到第2台服务器，以此类推。

然后设置一个时间参数，比如10分钟后，重新检测第1台服务器的可用性....

我认为这个故障转移策略是比较合理的，所有流量都只转发到一台服务器，并且冗余服务器作为备用。

**Comment by zephyrchien** [comment]
Hey @bingotl, this issue is duplicated with #82. For the feature requests, I would implement them when I have time ;)
