### ISSUE TITLE
VIRT 是不是分配的过高了

### ISSUE THREAD

**Issue by GouGoGoal** [zhboner/realm#15]
在虚拟机上测试转发10000-20000端口段，提示 memory allocation of 24 bytes failed
top命令中查看VIRT到了30G多，但实际的占用的内存不是很多
虚拟机的配置是4GBRAM+3GB SWAP，不知道要怎么改可以降低VIRT的分配，不然没办法正常跑起来

**Comment by zhboner** [comment]
已解决。
