### ISSUE TITLE
服务里边不支持配置文件吗

### ISSUE THREAD

**Issue by pxw2002** [zhboner/realm#17]
ExecStart=/usr/bin/realm -c config.json

启动失败
./realm -c config.json 是可以用的

**Comment by syuraking** [comment]
ExecStart=/usr/bin/realm -c /path/config.json

这不是低级问题？

**Comment by helloxz** [comment]
兄弟，注意`config.json`用绝对路径呀，确实是个低级问题。

**Comment by fengqi** [comment]
设置下工作路径也是可以用相对路径的
WorkingDirectory=/opt/xxx
