### ISSUE TITLE
Realm 无连接的情况下自动死亡

### ISSUE THREAD

**Issue by edmund-zhao** [zhboner/realm#22]
**Describe the bug**
在启动守护进程的情况下，如果长时间（5-15min）没有连接中转服务器，则会变成inactive，只能通过
`systemctl restart realm`
命令来手动重启！

系统：
Centos7 与 Ubuntu18 TLS

**Comment by edmund-zhao** [comment]
使用的模式是 配置文件模式
守护进程 启动执行：/usr/bin/realm -c /root/config.json

**Comment by BrunuhVille** [comment]
> 在启动守护进程的情况下，如果长时间（5-15min）没有连接中转服务器，则会变成inactive，只能通过

5-15min，这也太短了吧，难道要设置5分钟重启一次？

**Comment by edmund-zhao** [comment]
> > 在启动守护进程的情况下，如果长时间（5-15min）没有连接中转服务器，则会变成inactive，只能通过
> 
> 5-15min，这也太短了吧，难道要设置5分钟重启一次？

重要的，你无法确定它到底什么时候会挂，最短是5分钟，最长可以达到4h

**Comment by BrunuhVille** [comment]
> 重要的，你无法确定它到底什么时候会挂，最短是5分钟，最长可以达到4h

那你现在设置的是多长时间重启一次？

**Comment by edmund-zhao** [comment]
> > 重要的，你无法确定它到底什么时候会挂，最短是5分钟，最长可以达到4h
> 
> 那你现在设置的是多长时间重启一次？

我现在暂时在使用Iptables

**Comment by BrunuhVille** [comment]
> 我现在暂时在使用Iptables

用Iptables的话，bbr没有效果

**Comment by edmund-zhao** [comment]
对啊，我也想用realm啊，但就是不知道为什么不稳定😰，你们用的是配置文件吗？

在 2021年2月19日，上午12:55，BrunuhVille <notifications@github.com> 写道：

﻿
EXTERNAL EMAIL:

我现在暂时在使用Iptables

用Iptables的话，bbr没有效果

**Comment by BrunuhVille** [comment]
> 你们用的是配置文件吗？
我现在用realm管理脚本，图方便，https://github.com/seal0207/EasyRealM
可以设置多次时间重启一次，我设置3小时感觉还行
你觉得realm不稳的话，可以试试brook，之前用brook挺稳的

**Comment by edmund-zhao** [comment]
对，我就是这种情况，5个小时以内必定暴毙

在 2021年2月19日，上午1:11，BrunuhVille <notifications@github.com> 写道：

﻿
EXTERNAL EMAIL:

你们用的是配置文件吗？

我现在用realm管理脚本，图方便，https://github.com/seal0207/EasyRealM
可以设置多次时间重启一次，我设置3小时感觉还行
你觉得realm不稳的话，可以试试brook，之前用brook挺稳的

**Comment by Soniccube** [comment]
https://github.com/Soniccube/realm/releases/tag/1.2.1

可以测试该版本，应该修复了意外退出的问题。

**Comment by Soniccube** [comment]
#23

**Comment by edmund-zhao** [comment]
稳定测试3天，没有出现自动死亡的情况！这个版本完全解决了痛点👍

在 2021年4月6日，上午1:02，Soniccube ***@***.***> 写道：

﻿
EXTERNAL EMAIL:

https://github.com/Soniccube/realm/releases/tag/1.2.1

可以测试该版本，应该修复了意外退出的问题。
