### ISSUE TITLE
域名优先解析ipv4所带来的问题

### ISSUE THREAD

**Issue by notaganin** [zhboner/realm#24]
我在[Usage](https://github.com/zhboner/realm/blob/master/readme.md#usage)看到`If a domain is passed, the resolver will try to resolve and update the ip address regularly, ipv4 is preferred`，请问如何设置成ipv6优先？

**Comment by notaganin** [comment]
其实这个也算是一个bug.如果解析域名时优先ipv4，中转机用的是(或者只有)ipv6，就无法中转流量到落地机

**Comment by Soniccube** [comment]
> 其实这个也算是一个bug.如果解析域名时优先ipv4，中转机用的是ipv6，就无法中转流量到落地机

看了一下代码，ipv4  prefer的逻辑是一个域名同时有ipv4和ipv6解析的时候，优先使用ipv4，并非ipv6不可用。若relay机器ipv4不可达，应当不解析ipv4地址。

**Comment by zhboner** [comment]
现在不能设置解析的优先级，欢迎PR。

**Comment by zephyrchien** [comment]
这个问题只会出现在v4/v6双栈的机器上吧。（还是说只有IPv6的机器也能解析到A记录？）

如果要改DNS部分的话我建议做成ss-rust那样，用一个enum 涵盖IP地址/域名，避免每次发起连接/解析域名都要来回解析/拼接字符串
