### ISSUE TITLE
increase buffer size

### ISSUE THREAD

**Issue by zephyrchien** [zhboner/realm#32]
`tokio::io::copy` internally uses a hard-coded buffer(only 2k). It is too small. I would like to extend it to at least 4k, (or 16k which is better), so that a lot of(or maybe a few) syscall could be saved.

And we need to write our own copy fn. It is not complex, just like:
```rust
let mut buf = vec![0u8; 0x1000];
let mut n: usize;
loop {
    n = r.read(&mut buf).await?;
    if n==0 { break; }
    w.write(&buf[..n]).await?;
}
```

**Comment by zhboner** [comment]
Noted. This will be implemented in the next version. Thank you!
