### ISSUE TITLE
长时间转发会报错

### ISSUE THREAD

**Issue by atpdm** [zhboner/realm#34]
报错信息如下
TCP forward error 域名:端口，No file descriptors available (os error 24)
![图片](https://user-images.githubusercontent.com/86911170/127600779-f23460ff-758b-4173-a003-239e566363a5.png)

**Comment by zhboner** [comment]
请参照此网页优化你的服务器 https://github.com/shadowsocks/shadowsocks/wiki/Optimizing-Shadowsocks
