### ISSUE TITLE
支持TFO

### ISSUE THREAD

**Issue by zephyrchien** [zhboner/realm#40]
可以用ss-rust作者开源的这个库 [tokio-tfo](https://github.com/zonyitoo/tokio-tfo)，支持linux/win/bsd，跟ss-rust是相同的实现
建议把这个功能加入到features，默认关闭。有需要的用户可以加上`--features tfo` 参数自行编译
#13

**Comment by zephyrchien** [comment]
> 好奇这个项目原作者会弃坑么sweat_smile

@zhboner 說過他比較忙，我也是用愛發電=_=

**Comment by zephyrchien** [comment]
我在[這個倉庫](https://github.com/zephyrchien/realm/tree/3b0409b0f09474570642da6618ee4c95a4532506)添加了tfo支持，但是還沒有經過完整的測試。如果是Linux系統的話，需要kernel >= 4.11，不然`tfo`會跟`zero-copy`衝突(因爲第一次寫只能sendto, 不能splice)

**Comment by leonsyc** [comment]
> > 好奇这个项目原作者会弃坑么sweat_smile
> 
> @zhboner 說過他比較忙，我也是用愛發電=_=

大佬的fork支持v6转发吗。TFO没开过，听说可能导致容易被墙？

**Comment by zephyrchien** [comment]
> 大佬的fork支持v6转发吗。

支持的，`[::1]` `::1` 這兩種寫法都可以。如果轉發目標是域名，你還可以設置解析策略(比如ipv6優先或者僅限ipv6)

> TFO没开过，听说可能导致容易被墙？

確實有這種說法，但是每個人情況都不一樣。目前自動發佈的版本默認開啓了所有的features(udp, tfo, zero-copy)，等會我去把tfo改成默認關閉。
