### ISSUE TITLE
运行时报错

### ISSUE THREAD

**Issue by hzx8848** [zhboner/realm#45]
root@ubuntu:~# /usr/bin/realm -l 127.0.0.1:7890 -r x.x.x.x:443
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 98, kind: AddrInUse, message: "Address in use" }', src/relay.rs:51:69
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

请问这种情况该怎么解决？

**Comment by zephyrchien** [comment]
> Os { code: 98, kind: AddrInUse, message: "Address in use" }

**Comment by hzx8848** [comment]
尝试转发Trojan-Go似乎没成功，请问这个程序运行日志在哪看？

**Comment by zephyrchien** [comment]
> 尝试转发Trojan-Go似乎没成功，请问这个程序运行日志在哪看？

暂且没有日志功能。还是看客户端和服务端的日志吧，我猜你可能需要在客户端设置一下sni

**Comment by hzx8848** [comment]
sni设成啥？trojan-go的域名吗？

**Comment by zephyrchien** [comment]
> sni设成啥？trojan-go的域名吗？

跟服务端证书上的域名一致就行
