### ISSUE TITLE
docker镜像报错: Error response from daemon: Head https://ghcr.io/v2/zhboner/realm/manifests/latest: unauthorized.

### ISSUE THREAD

**Issue by noorzb** [zhboner/realm#61]
大佬你好，`realm`的**docker镜像**是不是没有**读取权限**呢？我直接运行`readme`示例：
```shell
docker run -d -p 9000:9000 ghcr.io/zhboner/realm:latest -l 0.0.0.0:9000 -r 192.168.233.2:9000
```
会得到如下报错：
```
Unable to find image 'ghcr.io/zhboner/realm:latest' locally
docker: Error response from daemon: Head https://ghcr.io/v2/zhboner/realm/manifests/latest: unauthorized.
See 'docker run --help'.
```
Google了一下，说是需要`personal access token (PAT)`才行，不过我创建了之后，重新拉取镜像，依然是报错：
```
Error response from daemon: unauthorized
```

**Comment by zephyrchien** [comment]
@noahziheng Need help

**Comment by zephyrchien** [comment]
Seems the package is private and not visible to the public. Let's wait for @zhboner to properly configure it.

**Comment by fjc0k** [comment]
```Dockerfile
FROM alpine:3.9

ARG VERSION="v2.3.4"

WORKDIR /realm

RUN wget https://github.com/zhboner/realm/releases/download/${VERSION}/realm-x86_64-unknown-linux-musl.tar.gz \
  && tar -zxvf realm-x86_64-unknown-linux-musl.tar.gz \
  && cp realm /usr/bin/realm \
  && chmod +x /usr/bin/realm

ENTRYPOINT ["/usr/bin/realm"]
```

**Comment by zurica2013** [comment]
感谢楼上。用这个Dockerfile构建了镜像和容器，但是程序跑不起来。
`exec /usr/bin/realm: no such file or directory`
`Error response from daemon: Container XXX is restarting, wait until the container is running`
换用 debian:bullseye-slim 做基础镜像就好了：
```dockerfile
FROM debian:bullseye-slim

ADD realm-x86_64-unknown-linux-gnu.tar.gz /usr/bin
RUN chmod +x /usr/bin/realm

ENTRYPOINT ["/usr/bin/realm"]
```

**Comment by whao** [comment]
Any updates on this issue?

**Comment by Skyxim** [comment]
> ![Screenshot from 2022-05-12 00-56-09](https://user-images.githubusercontent.com/51367850/167894504-b5d3b846-483f-4e87-a0f9-2473d7cd8141.png)

[Configuring access to packages for your personal account](https://docs.github.com/en/packages/learn-github-packages/configuring-a-packages-access-control-and-visibility#configuring-access-to-packages-for-your-personal-account)
change the visibility

**Comment by zurica2013** [comment]
老天，这个问题还没解决呢~~继续自己搞镜像吧

**Comment by Handsome1080P** [comment]
are u kidding me?first time on github?

**Comment by teamilkman** [comment]
不想开放就不要传github啊，搞这么老半天权限都不改

**Comment by zephyrchien** [comment]
Good news, I accidentally pushed a new image name and it defaults to public.

https://github.com/zhboner/realm/pkgs/container/realm2
```
docker run ghcr.io/zhboner/realm2:master
```
`realm2:latest` will be available after next release.
