### ISSUE TITLE
[问题] 负载均衡 是使用extra_remotes？

### ISSUE THREAD

**Issue by 07ke** [zhboner/realm#62]
负载均衡 是使用 extra_remotes ？

remote = "1.1.1.1:443"
extra_remotes = ["1.1.1.2:443", "1.1.1.3:443"]

如何配置负载均衡策略呢？

**Comment by zephyrchien** [comment]
需要自行编写hook，策略自定

**Comment by zephyrchien** [comment]
v2.4.0 已经内置负载均衡功能了:)
