### ISSUE TITLE
Debian 10 64位启动后无反应

### ISSUE THREAD

**Issue by zhucaidan** [zhboner/realm#7]
Debian 10 64位系统，下载最新版本，给权限后
设置端口转发无反应，检查realm进程占用0内存0CPU，端口检测没有开放
实际转发失败，程序并没有启动

**Comment by zhboner** [comment]
没有连接的时候占用确实是0，这是正常的。realm在debian 10下测试可以使用，请用netstat命令检查是否成功监听端口

**Comment by zhucaidan** [comment]
没有成功监听端口，代理工具连接到VPS端口显示不通，检测VPS的监听端口也是不可用的

**Comment by zhucaidan** [comment]
输入转发命令后回车，只会显示光标闪烁，然后就没有下文了，也没有运行日志

**Comment by zhboner** [comment]
没有运行日志说明是正常启动了，任何错误都会显示在命令行上。问题在于仅凭现在的信息我还不能定位错误。
