### ISSUE TITLE
华硕路由运行大概1分钟就会资源耗尽

### ISSUE THREAD

**Issue by fyhong** [zhboner/realm#72]
华硕ac68u等arm路由器运行一会就会出现以下提示，然后所有的基本命令都运行不了，只能重启路由解决 
Segmentation fault

**Comment by zephyrchien** [comment]
可能是连接数太多，fd用完了。 #60 #38 #34

**Comment by fyhong** [comment]
我中转socks5后，打开youtube，20秒都不用就会出现Segmentation fault
但我用另一个rust的程序
https://github.com/cedric05/tcp-relay-rust
这个就一直没问题。运行一天都不会出问题

**Comment by zephyrchien** [comment]
realm实现了tcp零拷贝，每条连接额外消耗4个fd. 我估计是路由器设默认的limit太小了(realm启动的时候会打印fd limit)

btw, 看日志很快就能定位问题

**Comment by fyhong** [comment]
这是启动日志

fd: soft=1024, hard=1024
log: level=off, output=stdout
dns: mode=ipv4_and_ipv6, protocol=tcp+udp, min-ttl=0, max-ttl=86400, cache-size=32, servers=system
inited: 0.0.0.0:2087 -> [game8.4pu.com:443]; options: send-proxy=false, send-proxy-version=2, accept-proxy=false, accept-proxy-timeout=5s; connect-timeout=5s, associate-timeout=30s;

**Comment by zephyrchien** [comment]
这是初始化信息。打开日志需要加--log-level参数，或者改配置文件，具体看文档

2022年6月18日(土) 午前0:49 fyhong ***@***.***>:
