### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by reformc** [zhboner/realm#75]
windows 10
version 1.62

the commands：
git clone https://github.com/zhboner/realm.git
cd realm
cargo build --release

then:
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> C:\Users\reform\.cargo\registry\src\github.com-1ecc6299db9ec823\realm_lb-0.1.0\src\lib.rs:1:12
  |
1 | #![feature(unchecked_math)]
  |            ^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `realm_lb` due to previous error

**Comment by zephyrchien** [comment]
https://github.com/zhboner/realm#build-guides

You should use nightly toolchain.
