### ISSUE TITLE
请教下能否设置黑名单，并且接入用户名密码认证？

### ISSUE THREAD

**Issue by mjh-jason** [zhboner/realm#77]
1.请教下能否设置黑名单，不允许访问某些网站
2.接入的能否要求用户名密码认证？
3.修改配置是否支持热加载？
谢谢哈~

**Comment by zephyrchien** [comment]
> 请教下能否设置黑名单，不允许访问某些网站

如果你是用realm来转发代理的话，realm并不能从加密的流量中获取到目标地址。你应该，也只能从代理后端入手。

> 接入的能否要求用户名密码认证

不能，即使利用hook也不行。目前realm的hook是只读的。如果用户以某种格式传入认证信息， 即使hook按照自定义逻辑分析了认证信息，放行了连接，转发至后端时依旧会连带上这部分额外信息。 

>修改配置是否支持热加载

不支持，除非将来有人愿意实现这个功能。我个人更倾向于提供API来调整转发规则。

如果你有定制化需求的话，建议自行fork一个分支。
