### ISSUE TITLE
openwrt x86里运行 转发udp出现错误

### ISSUE THREAD

**Issue by fedstryale** [zhboner/realm#8]
使用环境：
Openwrt Koolshare mod V2.31  X86-64

出现错误：

转发udp出现错误 `failed to send out UDP packet, Invalid argument (os error 22)`

**Comment by zhboner** [comment]
一般是绑定的本机ip不对造成的，设置成0.0.0.0试试

**Comment by fedstryale** [comment]
绑定的127.0.0.1，我先试下0.0.0.0

**Comment by zhboner** [comment]
需要绑定正确的接口，0.0.0.0是监听所有地址，所以没这个问题
