### ISSUE TITLE
我遇到了一个糟糕的问题，重名

### ISSUE THREAD

**Issue by aa51513** [zhboner/realm#85]
之前，由于个人需要，我在我的centos服务器上安装了realmd这个软件，安装命令是“yum -y install realmd”
其作用是将centos8加入到windows域中

不巧的是，realmd这个软件，占用了realm这个名字

导致我无法使用realm，来启动本项目生成的可执行包
这真的是太糟糕了
除了改文件的名字，是不是没有其他办法来解决这个问题了？

**Comment by zephyrchien** [comment]
You can execute Realm from absolute path, isn't it? And I don't think renaming Realm to whatever you like would be a problem?

**Comment by aa51513** [comment]
> You can execute Realm from absolute path, isn't it? And I don't think renaming Realm to whatever you like would be a problem?

got it，thank you for replying
