### ISSUE TITLE
可以支持这种格式吗

### ISSUE THREAD

**Issue by cjiasu** [zhboner/realm#9]
{
    "listening_addresses": ["0.0.0.0"], #监听IP
    "listening_ports": ["20000"],监听端口
    "remote_addresses": ["azure.alibaba.com"],#远程地址
    "remote_ports": ["20002"]#远程端口
}

{
    "listening_addresses": ["0.0.0.0"], #监听IP
    "listening_ports": ["20002-30000"],#监听端口
    "remote_addresses": ["azure-a.alibaba.com"],#远程地址
    "remote_ports": ["20002-30000"]#远程端口
}

可以支持这种配置文件吗  第一个单端口转发  第二个端口段

**Comment by zhboner** [comment]
以上两种是可以写在一起的吧

**Comment by cjiasu** [comment]
> 以上两种是可以写在一起的

这样比较清晰吧，如果单端口多的话，下个版本可以支持ws隧道转发吗

**Comment by zhboner** [comment]
那么完全可以启动两个进程，分别是单端口和多端口。现在的配置文件已经是非常灵活的格式了，我觉得没有必要增加复杂性。

> 下个版本可以支持ws隧道转发吗
能具体说说吗

**Comment by cjiasu** [comment]
你有QQ或者Tg吗 我有个类似程序发你看看

**Comment by zhboner** [comment]
realm转发的是tcp和udp流量，ws是应用层协议，所以是可以直接支持的
