### ISSUE TITLE
Does bidi_copy_buf can be used in any os

### ISSUE THREAD

**Issue by hzxuzhonghu** [zhboner/realm#90]
If not how could write code that can be run on any os?

**Comment by zephyrchien** [comment]
It depends on the `buffer` you provide. `Box<[u8]>` or other types which impl `AsMut<[u8]>`, and the associated `read`/`write` syscall can be found on any platform. However `unix pipe` is for unix, and `splice` is a linux-specific syscall.

**Comment by zephyrchien** [comment]
It is a one-line wrapper of copybuf. Please look into the source code.

**Comment by zephyrchien** [comment]
`bidi-zero-copy` is for linux only. You can use conditional compilation to fallback to `bidi-copy` on other platforms.

**Comment by zephyrchien** [comment]
https://github.com/zhboner/realm/blob/master/realm_core/src/tcp/plain.rs

**Comment by hzxuzhonghu** [comment]
Thanks for the clarification here
